alloc: Tried to simplify alloc info statements
So now:

  lfs3.c:11482:info: Rebuilding bmap (bmap 37/256)
  lfs3.c:11246:error: No more free space (lookahead 0/256)

Instead of the previously somewhat confusing:

  lfs3.c:11484:info: Rebuilding bmap (bmap 62/256/256)
  lfs3.c:11247:error: No more free space (lookahead 0/0/256)

While the previous info statements did have more info (window +
ckpoint + block count), usually one of these ended up redundant
(window == ckpoint == 0 during ENOSPC, for example).